Add terraform-backend-git remote state storage

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,5 @@
 circleci-image: &circleci-image
-  - image: fr123k/circleci-base:latest
+  - image: fr123k/circleci-golang:latest
 
 master-filter: &master-filter
   filters:
@@ -25,17 +25,6 @@ preflight-non-master-filter: &preflight-non-master-filter
 
 version: 2.1
 commands:
-  run-terraform-backend-git:
-    steps:
-      - add_ssh_keys:
-          fingerprints:
-            - "MD5:51:46:ee:a1:2d:3a:c4:7a:c9:b0:8d:9c:96:2e:e3:9d"
-      - run:
-          name: start terraform-backend-git
-          command: |
-
-            TF_BACKEND_HTTP_ENCRYPTION_PASSPHRASE=${TF_BACKEND_HTTP_ENCRYPTION_PASSPHRASE}  terraform-backend-git --access-logs &
-
   run-terraform-fmt:
     steps:
       - run:
@@ -60,15 +49,27 @@ commands:
         type: string
         default: "plan"
     steps:
+      - add_ssh_keys:
+          fingerprints:
+            - "90:f4:0e:ce:92:c1:ab:06:18:d6:08:6d:8b:31:df:e8"
+      - run:
+          name: start terraform-backend-git
+          command: |
+            ssh-add -L
+            ssh -v git@github.com || true
+
       - run:
           name: terraform plan
           command: |
             git_diff=<< parameters.git_diff >>
-
-            ls -lha ~/.ssh/
             rm -fv terraform-plan.out
+            # otherwise the go-git clone command fails
+            ssh-add -D
+            ssh-add /home/circleci/.ssh/id_rsa_90f40ece92c1ab0618d6086d8b31dfe8
 
             git --no-pager diff ${git_diff} --name-status --diff-filter=ACMR
+
+            TF_BACKEND_HTTP_ENCRYPTION_PASSPHRASE=${TF_BACKEND_HTTP_ENCRYPTION_PASSPHRASE} terraform-backend-git --access-logs &
 
             # iterate over the .tfvars and .tf changed files in this pr and try to run terraform plan
             for tfvarfile in $(git diff ${git_diff} --name-status --diff-filter=ACMR | awk '{print $2}' | grep -E "(.*.tf|.*.tfvars)"); do
@@ -83,7 +84,8 @@ commands:
               fi
 
               echo "Running Terraform plan for target: ${tfvarfile}"
-              make target=${tfvarfile} cliargs=-no-color tfinit tfplan 2>&1 | tee -a terraform-plan.out
+              terraform init 2>&1 | tee -a terraform-plan.out
+              terraform plan 2>&1 | tee -a terraform-plan.out
             done
 
   post-terraform-plan:
@@ -122,12 +124,23 @@ commands:
         type: string
         default: "apply"
     steps:
+      - add_ssh_keys:
+          fingerprints:
+            - "90:f4:0e:ce:92:c1:ab:06:18:d6:08:6d:8b:31:df:e8"
+      - run:
+          name: start terraform-backend-git
+          command: |
+            printenv | sort
+            echo ${SSH_AUTH_SOCK}
+            ssh-add -L
       - run:
           name: terraform apply
           command: |
             git_diff=<< parameters.git_diff >>
 
             rm -fv terraform-apply.out
+
+            TF_BACKEND_HTTP_ENCRYPTION_PASSPHRASE=${TF_BACKEND_HTTP_ENCRYPTION_PASSPHRASE} terraform-backend-git --access-logs &
 
             git --no-pager diff ${git_diff} --name-status --diff-filter=ACMR
 
@@ -160,7 +173,6 @@ jobs:
     resource_class: small
     steps:
       - checkout
-      - run-terraform-backend-git
       - run-terraform-plan
       - store_artifacts:
           path: ./terraform-plan.out
